# action.yml
name: 'Build / Publish docker images'
description: 'build and publish a docker image'
inputs:
  registery:
    description: 'registery url'
    required: false
  docker_repo:
    description: 'docker repo name for example docker/gcm'
    required: false
  context:  # location of dockerfile to be build
    description: 'location of dockerfile to be build'
    required: true
    default: '.'
  reg-username:
    description: 'registery username'
    required: false
  reg-password:
    description: 'registery username'
    required: false
  img-ver:
    description: 'docker image version'
    required: true
outputs:
  image-name: # id of output
    description: 'the name of the image that was built/published'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.registery }}
    - ${{ inputs.docker_repo }}
    - ${{ inputs.context }}
    - ${{ inputs.reg-username }}
    - ${{ inputs.reg-password }}
    - ${{ inputs.img-ver }}
